services:

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libuser
      MYSQL_PASSWORD: libpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  billing-service:
    build: ./billing-service
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8082/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  library-service-1:
    build: ./library-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      billing-service:
        condition: service_healthy

  library-service-2:
    build: ./library-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8081"
    depends_on:
      mysql:
        condition: service_healthy
      billing-service:
        condition: service_healthy

  library-service-3:
    build: ./library-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8081"
    depends_on:
      mysql:
        condition: service_healthy
      billing-service:
        condition: service_healthy

volumes:
  mysql_data:
